spring:
  application:
    name: springbatchdemo
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:in-mem-db
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
# Enable the below to get all the api-docs at <url>/api-docs.yml
# springdoc:
#   api-docs:
#     path: /api-docs
